/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 05 03:17:58 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Example_ESTest extends Example_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Example example0 = new Example();
      example0.test(10.644977332526446, 14.62669728, 0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Example example0 = new Example();
      example0.test(10.644977332526446, 14.62669728, 12);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Example example0 = new Example();
      example0.test(5.0, 14.62669728, 0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Example example0 = new Example();
      example0.test(1, 16.0, 2885);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-3006.31), 10.0, 33);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Example example0 = new Example();
      example0.test(9.965816208814458, 9.965816208814458, 1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Example example0 = new Example();
      example0.test(10.644977332526446, 14.62669728, (-1596));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Example example0 = new Example();
      example0.test(10.644977332526446, 15.0, 3);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Example example0 = new Example();
      example0.test(1, 10.644977332526446, (-2146796690));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Example example0 = new Example();
      example0.test(0.0, 2627.19, (-2146796690));
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-5577), (-1056.15637), 2261);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Example example0 = new Example();
      example0.test(10.644977332526446, 15.0, 1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Example example0 = new Example();
      example0.test(3990.36, 10.644977332526446, 578);
  }
}
