/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 05 03:05:22 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Example_ESTest extends Example_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-1.0), 16.0, 0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-1064), 10.0, (-1064));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Example example0 = new Example();
      example0.test(0.0, 0.0, 2434);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-1), 1459.4137293787767, (-1));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-2146411824), (-2146411824), (-2146411824));
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-2146411824), 14.50968392173, (-2146411824));
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Example example0 = new Example();
      example0.test(14.50968392173, 14.50968392173, (-2146411824));
  }
}
