/*
 * This file was automatically generated by EvoSuite
 * Sun Apr 05 03:33:28 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Example_ESTest extends Example_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Example example0 = new Example();
      example0.test(10.0, 15.511051901815845, 0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Example example0 = new Example();
      example0.test(15.511051901815845, 15.511051901815845, 6);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Example example0 = new Example();
      example0.test(20.0, 13, 232);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Example example0 = new Example();
      example0.test(5.0, 15.511051901815845, 1073741824);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Example example0 = new Example();
      example0.test(0.0, 16.0, 1640);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Example example0 = new Example();
      example0.test(0.0, 10.0, 26);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Example example0 = new Example();
      example0.test(10.0, 10.0, 0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Example example0 = new Example();
      example0.test(10.0, 15.511051901815845, (-4));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Example example0 = new Example();
      example0.test(10.0, 15.511051901815845, 3);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Example example0 = new Example();
      example0.test(26, 15.511051901815845, 859);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Example example0 = new Example();
      example0.test((-2317.88719336), 11, 11);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Example example0 = new Example();
      example0.test(13, 13, 1);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Example example0 = new Example();
      example0.test(13, 20.49790294045065, 0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Example example0 = new Example();
      example0.test(0.0, 0.0, 13);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Example example0 = new Example();
      example0.test(2757.826251258, (-1037.7698167656), 0);
  }
}
